version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

    # Allow auto-merge for patch and minor updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

    # Ignore major version updates so they won't be auto-merged
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

    # Enable auto-merge but only for minor and patch updates
    commit-message:
      prefix: "chore(deps):"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
    assignees:
      - "devchaudhary24k"
    reviewers:
      - "devchaudhary24k"
